# Generated by Django 5.0.6 on 2024-06-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.product",
                    ),
                ),
                ("flavor", models.CharField(max_length=255)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=("shop.product",),
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.product",
                    ),
                ),
                ("scent", models.CharField(max_length=255)),
            ],
            bases=("shop.product",),
        ),
        migrations.CreateModel(
            name="CrochetedItem",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.product",
                    ),
                ),
                ("yarn_type", models.CharField(max_length=255)),
            ],
            bases=("shop.product",),
        ),
        migrations.CreateModel(
            name="Crunchy",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.product",
                    ),
                ),
                ("ingredients", models.TextField()),
            ],
            bases=("shop.product",),
        ),
        migrations.CreateModel(
            name="ResinCraft",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.product",
                    ),
                ),
                ("material", models.CharField(max_length=255)),
            ],
            bases=("shop.product",),
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
